# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74461a22d04962078c70eb8a2a9f5866a7058d4def2d199d214a46d394f287b8fa4421b38f1e3b874695f5e3ed61b6bb03020912a796c2f970c6e8334638a639

test:
  secret_key_base: 6711b0829699436ef9929bb247959bb46b39ada76788b0448d2fc1e94d66f5f3bdb2f3797f6e8c57a34b70c89e14d8902fac50ddf1cfe0c96d636d12f692d1c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
